#!/usr/bin/env bash
# Script that manages a PID file and handles multiple signals
echo $$ > /tmp/myscript.pid

handle_sigterm() {
    echo "I hate the kill command"
    rm /tmp/myscript.pid
    exit
}

handle_sigquit() {
    rm /tmp/myscript.pid
    exit
}

trap 'handle_sigterm' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'handle_sigquit' SIGQUIT

while true
do
    echo "To infinity and beyond"
    sleep 2
done

